

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables: #Path to folder with .sln
  solution: RealRestaurant

stages: 
- stage: build
  jobs:
  - job: build
    
    steps:

    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(solution)