trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'RealRestaurant\RealRestaurant.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'jyalarcon1997'
    organization: '210726-wvu-net-ext'
    scannerMode: 'MSBuild'
    projectKey: '210726-wvu-net-ext_P1-Jorge-Yumiseba'
    projectName: 'P1-Jorge-Yumiseba'


- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**\*.sln'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*Test*.dll
     !**\obj\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'